'use strict';window.DOMHandler=class{constructor(f,e){this._iRuntime=f;this._componentId=e;this._hasTickCallback=!1;this._tickCallback=()=>this.Tick()}Attach(){}PostToRuntime(f,e,g,k){this._iRuntime.PostToRuntimeComponent(this._componentId,f,e,g,k)}PostToRuntimeAsync(f,e,g,k){return this._iRuntime.PostToRuntimeComponentAsync(this._componentId,f,e,g,k)}_PostToRuntimeMaybeSync(f,e,g){this._iRuntime.UsesWorker()?this.PostToRuntime(f,e,g):this._iRuntime._GetLocalRuntime()._OnMessageFromDOM({type:"event",
component:this._componentId,handler:f,dispatchOpts:g||null,data:e,responseId:null})}AddRuntimeMessageHandler(f,e){this._iRuntime.AddRuntimeComponentMessageHandler(this._componentId,f,e)}AddRuntimeMessageHandlers(f){for(const [e,g]of f)this.AddRuntimeMessageHandler(e,g)}GetRuntimeInterface(){return this._iRuntime}GetComponentID(){return this._componentId}_StartTicking(){this._hasTickCallback||(this._iRuntime._AddRAFCallback(this._tickCallback),this._hasTickCallback=!0)}_StopTicking(){this._hasTickCallback&&
(this._iRuntime._RemoveRAFCallback(this._tickCallback),this._hasTickCallback=!1)}Tick(){}};
window.RateLimiter=class{constructor(f,e){this._callback=f;this._interval=e;this._timerId=-1;this._lastCallTime=-Infinity;this._timerCallFunc=()=>this._OnTimer();this._canRunImmediate=this._ignoreReset=!1}SetCanRunImmediate(f){this._canRunImmediate=!!f}Call(){if(-1===this._timerId){var f=Date.now(),e=f-this._lastCallTime,g=this._interval;e>=g&&this._canRunImmediate?(this._lastCallTime=f,this._RunCallback()):this._timerId=self.setTimeout(this._timerCallFunc,Math.max(g-e,4))}}_RunCallback(){this._ignoreReset=
!0;this._callback();this._ignoreReset=!1}Reset(){this._ignoreReset||(this._CancelTimer(),this._lastCallTime=Date.now())}_OnTimer(){this._timerId=-1;this._lastCallTime=Date.now();this._RunCallback()}_CancelTimer(){-1!==this._timerId&&(self.clearTimeout(this._timerId),this._timerId=-1)}Release(){this._CancelTimer();this._timerCallFunc=this._callback=null}};"use strict";
window.DOMElementHandler=class extends self.DOMHandler{constructor(f,e){super(f,e);this._elementMap=new Map;this._autoAttach=!0;this.AddRuntimeMessageHandlers([["create",g=>this._OnCreate(g)],["destroy",g=>this._OnDestroy(g)],["set-visible",g=>this._OnSetVisible(g)],["update-position",g=>this._OnUpdatePosition(g)],["update-state",g=>this._OnUpdateState(g)],["focus",g=>this._OnSetFocus(g)],["set-css-style",g=>this._OnSetCssStyle(g)],["set-attribute",g=>this._OnSetAttribute(g)],["remove-attribute",
g=>this._OnRemoveAttribute(g)]]);this.AddDOMElementMessageHandler("get-element",g=>g)}SetAutoAttach(f){this._autoAttach=!!f}AddDOMElementMessageHandler(f,e){this.AddRuntimeMessageHandler(f,g=>{const k=this._elementMap.get(g.elementId);return e(k,g)})}_OnCreate(f){const e=f.elementId,g=this.CreateElement(e,f);this._elementMap.set(e,g);f.isVisible||(g.style.display="none");f=this._GetFocusElement(g);f.addEventListener("focus",k=>this._OnFocus(e));f.addEventListener("blur",k=>this._OnBlur(e));this._autoAttach&&
document.body.appendChild(g)}CreateElement(f,e){throw Error("required override");}DestroyElement(f){}_OnDestroy(f){f=f.elementId;const e=this._elementMap.get(f);this.DestroyElement(e);this._autoAttach&&e.parentElement.removeChild(e);this._elementMap.delete(f)}PostToRuntimeElement(f,e,g){g||(g={});g.elementId=e;this.PostToRuntime(f,g)}_PostToRuntimeElementMaybeSync(f,e,g){g||(g={});g.elementId=e;this._PostToRuntimeMaybeSync(f,g)}_OnSetVisible(f){this._autoAttach&&(this._elementMap.get(f.elementId).style.display=
f.isVisible?"":"none")}_OnUpdatePosition(f){if(this._autoAttach){var e=this._elementMap.get(f.elementId);e.style.left=f.left+"px";e.style.top=f.top+"px";e.style.width=f.width+"px";e.style.height=f.height+"px";f=f.fontSize;null!==f&&(e.style.fontSize=f+"em")}}_OnUpdateState(f){const e=this._elementMap.get(f.elementId);this.UpdateState(e,f)}UpdateState(f,e){throw Error("required override");}_GetFocusElement(f){return f}_OnFocus(f){this.PostToRuntimeElement("elem-focused",f)}_OnBlur(f){this.PostToRuntimeElement("elem-blurred",
f)}_OnSetFocus(f){const e=this._GetFocusElement(this._elementMap.get(f.elementId));f.focus?e.focus():e.blur()}_OnSetCssStyle(f){this._elementMap.get(f.elementId).style[f.prop]=f.val}_OnSetAttribute(f){this._elementMap.get(f.elementId).setAttribute(f.name,f.val)}_OnRemoveAttribute(f){this._elementMap.get(f.elementId).removeAttribute(f.name)}GetElementById(f){return this._elementMap.get(f)}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let e=0;function g(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.isStringSrc?new Promise(c=>{const d="c3_resolve_"+e;++e;self[d]=c;a.textContent=b.str+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let k=!1,r=!1;function y(){if(!k){try{new Worker("blob://",{get type(){r=!0}})}catch(b){}k=!0}return r}
let p=new Audio;const v={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function q(b){b=await E(b);return(new TextDecoder("utf-8")).decode(b)}function E(b){return new Promise((a,
c)=>{const d=new FileReader;d.onload=h=>a(h.target.result);d.onerror=h=>c(h);d.readAsArrayBuffer(b)})}const z=[];let w=0;window.RealFile=window.File;const x=[],A=new Map,B=new Map;let u=0;const C=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");C.push(b)};const D=new Set(["cordova","playable-ad","instant-games"]);function F(b){return D.has(b)}let G=!1;window.RuntimeInterface=class b{constructor(a){this._useWorker=a.useWorker;this._messageChannelPort=
null;this._baseUrl="";this._scriptFolder=a.scriptFolder;this._workerScriptURLs={};this._localRuntime=this._worker=null;this._domHandlers=[];this._jobScheduler=this._canvas=this._runtimeDomHandler=null;this._rafId=-1;this._rafFunc=()=>this._OnRAFCallback();this._rafCallbacks=[];this._exportType=a.exportType;!this._useWorker||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&y()||(this._useWorker=!1);F(this._exportType)&&this._useWorker&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),
this._useWorker=!1);this._localFileStrings=this._localFileBlobs=null;"html5"!==this._exportType&&"playable-ad"!==this._exportType||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.AddRuntimeComponentMessageHandler("runtime","cordova-fetch-local-file",c=>this._OnCordovaFetchLocalFile(c));this.AddRuntimeComponentMessageHandler("runtime","create-job-worker",
c=>this._OnCreateJobWorker(c));"cordova"===this._exportType?document.addEventListener("deviceready",()=>this._Init(a)):this._Init(a)}Release(){this._CancelAnimationFrame();this._messageChannelPort&&(this._messageChannelPort=this._messageChannelPort.onmessage=null);this._worker&&(this._worker.terminate(),this._worker=null);this._localRuntime&&(this._localRuntime.Release(),this._localRuntime=null);this._canvas&&(this._canvas.parentElement.removeChild(this._canvas),this._canvas=null)}GetCanvas(){return this._canvas}GetBaseURL(){return this._baseUrl}UsesWorker(){return this._useWorker}GetExportType(){return this._exportType}GetScriptFolder(){return this._scriptFolder}IsiOSCordova(){return f&&
"cordova"===this._exportType}IsiOSWebView(){return f&&F(this._exportType)||navigator.standalone}async _Init(a){"macos-wkwebview"===this._exportType&&this._SendWrapperMessage({type:"ready"});if("playable-ad"===this._exportType){this._localFileBlobs=self.c3_base64files;this._localFileStrings={};await this._ConvertDataUrisToBlobs();for(let d=0,h=a.engineScripts.length;d<h;++d){var c=a.engineScripts[d].toLowerCase();this._localFileStrings.hasOwnProperty(c)?a.engineScripts[d]={isStringSrc:!0,str:this._localFileStrings[c]}:
this._localFileBlobs.hasOwnProperty(c)&&(a.engineScripts[d]=URL.createObjectURL(this._localFileBlobs[c]))}}a.baseUrl?this._baseUrl=a.baseUrl:(c=location.origin,this._baseUrl=("null"===c?"file:///":c)+location.pathname,c=this._baseUrl.lastIndexOf("/"),-1!==c&&(this._baseUrl=this._baseUrl.substr(0,c+1)));a.workerScripts&&(this._workerScriptURLs=a.workerScripts);c=new MessageChannel;this._messageChannelPort=c.port1;this._messageChannelPort.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&
window.c3_addPortMessageHandler(d=>this._OnMessageFromDebugger(d));this._jobScheduler=new self.JobSchedulerDOM(this);await this._jobScheduler.Init();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this._useWorker?await this._InitWorker(a,c.port2):await this._InitDOM(a,c.port2)}_GetWorkerURL(a){a=this._workerScriptURLs.hasOwnProperty(a)?this._workerScriptURLs[a]:a.endsWith("/workermain.js")&&this._workerScriptURLs.hasOwnProperty("workermain.js")?
this._workerScriptURLs["workermain.js"]:"playable-ad"===this._exportType&&this._localFileBlobs.hasOwnProperty(a.toLowerCase())?this._localFileBlobs[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async CreateWorker(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if(this.IsiOSCordova()&&"file:"===location.protocol)return a=await this.CordovaFetchLocalFileAsArrayBuffer(this._scriptFolder+a),a=new Blob([a],{type:"application/javascript"}),new Worker(URL.createObjectURL(a),
d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),d)}return new Worker(a,d)}_GetWindowInnerWidth(){return Math.max(window.innerWidth,1)}_GetWindowInnerHeight(){return Math.max(window.innerHeight,1)}_GetCommonRuntimeOptions(a){return{baseUrl:this._baseUrl,windowInnerWidth:this._GetWindowInnerWidth(),windowInnerHeight:this._GetWindowInnerHeight(),devicePixelRatio:window.devicePixelRatio,
isFullscreen:b.IsDocumentFullscreen(),projectData:a.projectData,previewImageBlobs:window.cr_previewImageBlobs||this._localFileBlobs,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,swClientId:window.cr_swClientId||"",exportType:a.exportType,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.ife,jobScheduler:this._jobScheduler.GetPortData(),supportedAudioFormats:v,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this._scriptFolder+
"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this._scriptFolder+"opus.wasm.wasm",isiOSCordova:this.IsiOSCordova(),isiOSWebView:this.IsiOSWebView(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async _InitWorker(a,c){var d=this._GetWorkerURL(a.workerMainUrl);this._worker=await this.CreateWorker(d,this._baseUrl,{type:"module",name:"Runtime"});this._canvas=document.createElement("canvas");this._canvas.style.display="none";d=this._canvas.transferControlToOffscreen();document.body.appendChild(this._canvas);
window.c3canvas=this._canvas;this._worker.postMessage(Object.assign(this._GetCommonRuntimeOptions(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:a.workerDependencyScripts||[],engineScripts:a.engineScripts,projectScripts:a.projectScripts,mainProjectScript:a.mainProjectScript,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...this._jobScheduler.GetPortTransferables()]);this._domHandlers=x.map(h=>new h(this));this._FindRuntimeDOMHandler();self.c3_callFunction=
(h,l)=>this._runtimeDomHandler._InvokeFunctionFromJS(h,l);"preview"===this._exportType&&(self.goToLastErrorScript=()=>this.PostToRuntimeComponent("runtime","go-to-last-error-script"))}async _InitDOM(a,c){this._canvas=document.createElement("canvas");this._canvas.style.display="none";document.body.appendChild(this._canvas);window.c3canvas=this._canvas;this._domHandlers=x.map(m=>new m(this));this._FindRuntimeDOMHandler();var d=a.engineScripts.map(m=>"string"===typeof m?(new URL(m,this._baseUrl)).toString():
m);Array.isArray(a.workerDependencyScripts)&&d.unshift(...a.workerDependencyScripts);d=await Promise.all(d.map(m=>this._MaybeGetCordovaScriptURL(m)));await Promise.all(d.map(m=>g(m)));d=self.C3_ProjectScriptsStatus;const h=a.mainProjectScript,l=a.projectScripts;for(let [m,n]of l)if(n||(n=m),m===h)try{n=await this._MaybeGetCordovaScriptURL(n),await g(n),"preview"!==this._exportType||d[m]||this._ReportProjectMainScriptError(m,"main script did not run to completion")}catch(t){this._ReportProjectMainScriptError(m,
t)}else if("scriptsInEvents.js"===m||m.endsWith("/scriptsInEvents.js"))n=await this._MaybeGetCordovaScriptURL(n),await g(n);"preview"===this._exportType&&"object"!==typeof self.C3.ScriptsInEvents?(this._RemoveLoadingMessage(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this._GetCommonRuntimeOptions(a),
{isInWorker:!1,messagePort:c,canvas:this._canvas,runOnStartupFunctions:C}),this._OnBeforeCreateRuntime(),this._localRuntime=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this._localRuntime,a))}_ReportProjectMainScriptError(a,c){this._RemoveLoadingMessage();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}_OnBeforeCreateRuntime(){this._RemoveLoadingMessage()}_RemoveLoadingMessage(){const a=
window.cr_previewLoadingElem;a&&(a.parentElement.removeChild(a),window.cr_previewLoadingElem=null)}async _OnCreateJobWorker(a){a=await this._jobScheduler._CreateJobWorker();return{outputPort:a,transferables:[a]}}_GetLocalRuntime(){if(this._useWorker)throw Error("not available in worker mode");return this._localRuntime}PostToRuntimeComponent(a,c,d,h,l){this._messageChannelPort.postMessage({type:"event",component:a,handler:c,dispatchOpts:h||null,data:d,responseId:null},l)}PostToRuntimeComponentAsync(a,
c,d,h,l){const m=u++,n=new Promise((t,H)=>{B.set(m,{resolve:t,reject:H})});this._messageChannelPort.postMessage({type:"event",component:a,handler:c,dispatchOpts:h||null,data:d,responseId:m},l);return n}["_OnMessageFromRuntime"](a){const c=a.type;if("event"===c)return this._OnEventFromRuntime(a);if("result"===c)this._OnResultFromRuntime(a);else if("runtime-ready"===c)this._OnRuntimeReady();else if("alert-error"===c)this._RemoveLoadingMessage(),alert(a.message);else if("creating-runtime"===c)this._OnBeforeCreateRuntime();
else throw Error(`unknown message '${c}'`);}_OnEventFromRuntime(a){const c=a.component,d=a.handler,h=a.data,l=a.responseId;if(a=A.get(c))if(a=a.get(d)){var m=null;try{m=a(h)}catch(n){console.error(`Exception in '${c}' handler '${d}':`,n);null!==l&&this._PostResultToRuntime(l,!1,""+n);return}if(null===l)return m;m&&m.then?m.then(n=>this._PostResultToRuntime(l,!0,n)).catch(n=>{console.error(`Rejection from '${c}' handler '${d}':`,n);this._PostResultToRuntime(l,!1,""+n)}):this._PostResultToRuntime(l,
!0,m)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}_PostResultToRuntime(a,c,d){let h;d&&d.transferables&&(h=d.transferables);this._messageChannelPort.postMessage({type:"result",responseId:a,isOk:c,result:d},h)}_OnResultFromRuntime(a){const c=a.responseId,d=a.isOk;a=a.result;const h=B.get(c);d?h.resolve(a):h.reject(a);B.delete(c)}AddRuntimeComponentMessageHandler(a,c,d){let h=A.get(a);h||(h=new Map,A.set(a,h));if(h.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);
h.set(c,d)}static AddDOMHandlerClass(a){if(x.includes(a))throw Error("DOM handler already added");x.push(a)}_FindRuntimeDOMHandler(){for(const a of this._domHandlers)if("runtime"===a.GetComponentID()){this._runtimeDomHandler=a;return}throw Error("cannot find runtime DOM handler");}_OnMessageFromDebugger(a){this.PostToRuntimeComponent("debugger","message",a)}_OnRuntimeReady(){for(const a of this._domHandlers)a.Attach()}static IsDocumentFullscreen(){return!!(document.fullscreenElement||document.webkitFullscreenElement||
document.mozFullScreenElement||G)}static _SetWrapperIsFullscreenFlag(a){G=!!a}async GetRemotePreviewStatusInfo(){return await this.PostToRuntimeComponentAsync("runtime","get-remote-preview-status-info")}_AddRAFCallback(a){this._rafCallbacks.push(a);this._RequestAnimationFrame()}_RemoveRAFCallback(a){a=this._rafCallbacks.indexOf(a);if(-1===a)throw Error("invalid callback");this._rafCallbacks.splice(a,1);this._rafCallbacks.length||this._CancelAnimationFrame()}_RequestAnimationFrame(){-1===this._rafId&&
this._rafCallbacks.length&&(this._rafId=requestAnimationFrame(this._rafFunc))}_CancelAnimationFrame(){-1!==this._rafId&&(cancelAnimationFrame(this._rafId),this._rafId=-1)}_OnRAFCallback(){this._rafId=-1;for(const a of this._rafCallbacks)a();this._RequestAnimationFrame()}TryPlayMedia(a){this._runtimeDomHandler.TryPlayMedia(a)}RemovePendingPlay(a){this._runtimeDomHandler.RemovePendingPlay(a)}_PlayPendingMedia(){this._runtimeDomHandler._PlayPendingMedia()}SetSilent(a){this._runtimeDomHandler.SetSilent(a)}IsAudioFormatSupported(a){return!!v[a]}async _WasmDecodeWebMOpus(a){a=
await this.PostToRuntimeComponentAsync("runtime","opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}IsAbsoluteURL(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}IsRelativeURL(a){return!this.IsAbsoluteURL(a)}async _MaybeGetCordovaScriptURL(a){return"cordova"===this._exportType&&(a.startsWith("file:")||"file:"===location.protocol&&this.IsRelativeURL(a))?(a.startsWith(this._baseUrl)&&(a=a.substr(this._baseUrl.length)),a=await this.CordovaFetchLocalFileAsArrayBuffer(a),
a=new Blob([a],{type:"application/javascript"}),URL.createObjectURL(a)):a}async _OnCordovaFetchLocalFile(a){const c=a.filename;switch(a.as){case "text":return await this.CordovaFetchLocalFileAsText(c);case "buffer":return await this.CordovaFetchLocalFileAsArrayBuffer(c);default:throw Error("unsupported type");}}_GetPermissionAPI(){const a=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof a)throw Error("Permission API is not loaded");return a}_MapPermissionID(a,
c){a=a[c];if("string"!==typeof a)throw Error("Invalid permission name");return a}_HasPermission(a){const c=this._GetPermissionAPI();return new Promise((d,h)=>c.checkPermission(this._MapPermissionID(c,a),l=>d(!!l.hasPermission),h))}_RequestPermission(a){const c=this._GetPermissionAPI();return new Promise((d,h)=>c.requestPermission(this._MapPermissionID(c,a),l=>d(!!l.hasPermission),h))}async RequestPermissions(a){if("cordova"!==this.GetExportType()||this.IsiOSCordova())return!0;for(const c of a)if(!await this._HasPermission(c)&&
!1===await this._RequestPermission(c))return!1;return!0}async RequirePermissions(...a){if(!1===await this.RequestPermissions(a))throw Error("Permission not granted");}CordovaFetchLocalFile(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,h)=>{window.resolveLocalFileSystemURL(c,l=>{l.file(d,h)},h)})}async CordovaFetchLocalFileAsText(a){a=await this.CordovaFetchLocalFile(a);return await q(a)}_CordovaMaybeStartNextArrayBufferRead(){if(z.length&&!(8<=w)){w++;
var a=z.shift();this._CordovaDoFetchLocalFileAsAsArrayBuffer(a.filename,a.successCallback,a.errorCallback)}}CordovaFetchLocalFileAsArrayBuffer(a){return new Promise((c,d)=>{z.push({filename:a,successCallback:h=>{w--;this._CordovaMaybeStartNextArrayBufferRead();c(h)},errorCallback:h=>{w--;this._CordovaMaybeStartNextArrayBufferRead();d(h)}});this._CordovaMaybeStartNextArrayBufferRead()})}async _CordovaDoFetchLocalFileAsAsArrayBuffer(a,c,d){try{const h=await this.CordovaFetchLocalFile(a),l=await E(h);
c(l)}catch(h){d(h)}}_SendWrapperMessage(a){if("windows-webview2"===this._exportType)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this._exportType)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async _ConvertDataUrisToBlobs(){const a=[];for(const [c,d]of Object.entries(this._localFileBlobs))a.push(this._ConvertDataUriToBlobs(c,d));await Promise.all(a)}async _ConvertDataUriToBlobs(a,c){if("object"===
typeof c)this._localFileBlobs[a]=new Blob([c.str],{type:c.type}),this._localFileStrings[a]=c.str;else{let d=await this._FetchDataUri(c);d||(d=this._DataURIToBinaryBlobSync(c));this._localFileBlobs[a]=d}}async _FetchDataUri(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}_DataURIToBinaryBlobSync(a){a=
this._ParseDataURI(a);return this._BinaryStringToBlob(a.data,a.mime_type)}_ParseDataURI(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");var d=a.substring(5,c);a=a.substring(c+1);c=d.split(";");d=c[0]||"";const h=c[2];a="base64"===c[1]||"base64"===h?atob(a):decodeURIComponent(a);return{mime_type:d,data:a}}_BinaryStringToBlob(a,c){var d=a.length;let h=d>>2,l=new Uint8Array(d),m=new Uint32Array(l.buffer,0,h),n,t;for(t=n=0;n<h;++n)m[n]=a.charCodeAt(t++)|a.charCodeAt(t++)<<
8|a.charCodeAt(t++)<<16|a.charCodeAt(t++)<<24;for(d&=3;d--;)l[t]=a.charCodeAt(t),++t;return new Blob([l],{type:c})}}}"use strict";
{const f=self.RuntimeInterface;function e(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const g=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),k={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},r={dispatchUserScriptEvent:!0},y={dispatchRuntimeEvent:!0};function p(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=
h=>c(h);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function v(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=h=>c(h);d.src=b})}async function q(b){b=URL.createObjectURL(b);try{return await v(b)}finally{URL.revokeObjectURL(b)}}function E(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=h=>a(h.target.result);d.onerror=h=>c(h);d.readAsText(b)})}async function z(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await q(b);var d=await E(b);d=
(new DOMParser).parseFromString(d,"image/svg+xml");const h=d.documentElement;if(h.hasAttribute("width")&&h.hasAttribute("height")){const l=h.getAttribute("width"),m=h.getAttribute("height");if(!l.includes("%")&&!m.includes("%"))return await q(b)}h.setAttribute("width",a+"px");h.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await q(b)}function w(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);
return!1}const x=new Set(["input","textarea","datalist","select"]);function A(b){return x.has(b.tagName.toLowerCase())||w(b)}const B=new Set(["canvas","body","html"]);function u(b){const a=b.target.tagName.toLowerCase();B.has(a)&&b.preventDefault()}function C(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}self.C3_GetSvgImageSize=async function(b){b=await q(b);if(0<b.width&&0<b.height)return[b.width,b.height];{b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";
document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]}};self.C3_RasterSvgImageBlob=async function(b,a,c,d,h){b=await z(b,a,c);const l=document.createElement("canvas");l.width=d;l.height=h;l.getContext("2d").drawImage(b,0,0,a,c);return l};let D=!1;document.addEventListener("pause",()=>D=!0);document.addEventListener("resume",()=>D=!1);function F(){try{return window.parent&&window.parent.document.hasFocus()}catch(b){return!1}}function G(){const b=
document.activeElement;if(!b)return!1;const a=b.tagName.toLowerCase(),c=new Set("email number password search tel text url".split(" "));return"textarea"===a?!0:"input"===a?c.has(b.type.toLowerCase()||"text"):w(b)}f.AddDOMHandlerClass(class extends self.DOMHandler{constructor(b){super(b,"runtime");this._isFirstSizeUpdate=!0;this._simulatedResizeTimerId=-1;this._targetOrientation="any";this._attachedDeviceMotionEvent=this._attachedDeviceOrientationEvent=!1;this._lastPointerRawUpdateEvent=this._pointerRawUpdateRateLimiter=
this._debugHighlightElem=null;b.AddRuntimeComponentMessageHandler("canvas","update-size",d=>this._OnUpdateCanvasSize(d));b.AddRuntimeComponentMessageHandler("runtime","invoke-download",d=>this._OnInvokeDownload(d));b.AddRuntimeComponentMessageHandler("runtime","raster-svg-image",d=>this._OnRasterSvgImage(d));b.AddRuntimeComponentMessageHandler("runtime","get-svg-image-size",d=>this._OnGetSvgImageSize(d));b.AddRuntimeComponentMessageHandler("runtime","set-target-orientation",d=>this._OnSetTargetOrientation(d));
b.AddRuntimeComponentMessageHandler("runtime","register-sw",()=>this._OnRegisterSW());b.AddRuntimeComponentMessageHandler("runtime","post-to-debugger",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","go-to-script",d=>this._OnPostToDebugger(d));b.AddRuntimeComponentMessageHandler("runtime","before-start-ticking",()=>this._OnBeforeStartTicking());b.AddRuntimeComponentMessageHandler("runtime","debug-highlight",d=>this._OnDebugHighlight(d));b.AddRuntimeComponentMessageHandler("runtime",
"enable-device-orientation",()=>this._AttachDeviceOrientationEvent());b.AddRuntimeComponentMessageHandler("runtime","enable-device-motion",()=>this._AttachDeviceMotionEvent());b.AddRuntimeComponentMessageHandler("runtime","add-stylesheet",d=>this._OnAddStylesheet(d));b.AddRuntimeComponentMessageHandler("runtime","alert",d=>this._OnAlert(d));b.AddRuntimeComponentMessageHandler("runtime","hide-cordova-splash",()=>this._OnHideCordovaSplash());const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",
d=>{const h=d.target,l=h.tagName.toLowerCase();a.has(l)||w(h)||d.preventDefault()});const c=b.GetCanvas();window.addEventListener("selectstart",u);window.addEventListener("gesturehold",u);c.addEventListener("selectstart",u);c.addEventListener("gesturehold",u);window.addEventListener("touchstart",u,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",u,{passive:!1}),c.addEventListener("pointerdown",u)):c.addEventListener("touchstart",u);this._mousePointerLastButtons=
0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",C,{passive:!1});window.addEventListener("wheel",C,{passive:!1});window.addEventListener("resize",()=>this._OnWindowResize());window.addEventListener("fullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("webkitfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("mozfullscreenchange",()=>this._OnFullscreenChange());window.addEventListener("fullscreenerror",
d=>this._OnFullscreenError(d));window.addEventListener("webkitfullscreenerror",d=>this._OnFullscreenError(d));window.addEventListener("mozfullscreenerror",d=>this._OnFullscreenError(d));b.IsiOSWebView()&&window.addEventListener("focusout",()=>{G()||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>this._OnWrapperMessage(d);this._mediaPendingPlay=new Set;this._mediaRemovedPendingPlay=new WeakSet;this._isSilent=!1}_OnBeforeStartTicking(){"cordova"===this._iRuntime.GetExportType()?
(document.addEventListener("pause",()=>this._OnVisibilityChange(!0)),document.addEventListener("resume",()=>this._OnVisibilityChange(!1))):document.addEventListener("visibilitychange",()=>this._OnVisibilityChange(document.hidden));return{isSuspended:!(!document.hidden&&!D)}}Attach(){window.addEventListener("focus",()=>this._PostRuntimeEvent("window-focus"));window.addEventListener("blur",()=>{this._PostRuntimeEvent("window-blur",{parentHasFocus:F()});this._mousePointerLastButtons=0});window.addEventListener("focusin",
a=>{A(a.target)&&this._PostRuntimeEvent("keyboard-blur")});window.addEventListener("keydown",a=>this._OnKeyEvent("keydown",a));window.addEventListener("keyup",a=>this._OnKeyEvent("keyup",a));window.addEventListener("dblclick",a=>this._OnMouseEvent("dblclick",a,k));window.addEventListener("wheel",a=>this._OnMouseWheelEvent("wheel",a));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{this._HandlePointerDownFocus(a);this._OnPointerEvent("pointerdown",a)}),this._iRuntime.UsesWorker()&&
"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this._pointerRawUpdateRateLimiter=new self.RateLimiter(()=>this._DoSendPointerRawUpdate(),5),this._pointerRawUpdateRateLimiter.SetCanRunImmediate(!0),window.addEventListener("pointerrawupdate",a=>this._OnPointerRawUpdate(a))):window.addEventListener("pointermove",a=>this._OnPointerEvent("pointermove",a)),window.addEventListener("pointerup",a=>this._OnPointerEvent("pointerup",a)),window.addEventListener("pointercancel",a=>this._OnPointerEvent("pointercancel",
a))):(window.addEventListener("mousedown",a=>{this._HandlePointerDownFocus(a);this._OnMouseEventAsPointer("pointerdown",a)}),window.addEventListener("mousemove",a=>this._OnMouseEventAsPointer("pointermove",a)),window.addEventListener("mouseup",a=>this._OnMouseEventAsPointer("pointerup",a)),window.addEventListener("touchstart",a=>{this._HandlePointerDownFocus(a);this._OnTouchEvent("pointerdown",a)}),window.addEventListener("touchmove",a=>this._OnTouchEvent("pointermove",a)),window.addEventListener("touchend",
a=>this._OnTouchEvent("pointerup",a)),window.addEventListener("touchcancel",a=>this._OnTouchEvent("pointercancel",a)));const b=()=>this._PlayPendingMedia();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0)}_PostRuntimeEvent(b,a){this.PostToRuntime(b,a||null,y)}_GetWindowInnerWidth(){return this._iRuntime._GetWindowInnerWidth()}_GetWindowInnerHeight(){return this._iRuntime._GetWindowInnerHeight()}_OnWindowResize(){const b=
this._GetWindowInnerWidth(),a=this._GetWindowInnerHeight();this._PostRuntimeEvent("window-resize",{innerWidth:b,innerHeight:a,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen()});this._iRuntime.IsiOSWebView()&&(-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId),this._OnSimulatedResize(b,a,0))}_ScheduleSimulatedResize(b,a,c){-1!==this._simulatedResizeTimerId&&clearTimeout(this._simulatedResizeTimerId);this._simulatedResizeTimerId=setTimeout(()=>
this._OnSimulatedResize(b,a,c),48)}_OnSimulatedResize(b,a,c){const d=this._GetWindowInnerWidth(),h=this._GetWindowInnerHeight();this._simulatedResizeTimerId=-1;d!=b||h!=a?this._PostRuntimeEvent("window-resize",{innerWidth:d,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.IsDocumentFullscreen()}):10>c&&this._ScheduleSimulatedResize(d,h,c+1)}_OnSetTargetOrientation(b){this._targetOrientation=b.targetOrientation}_TrySetTargetOrientation(){const b=this._targetOrientation;if(screen.orientation&&
screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",a)}}_OnFullscreenChange(){const b=
f.IsDocumentFullscreen();b&&"any"!==this._targetOrientation&&this._TrySetTargetOrientation();this.PostToRuntime("fullscreenchange",{isFullscreen:b,innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnFullscreenError(b){console.warn("[Construct 3] Fullscreen request failed: ",b);this.PostToRuntime("fullscreenerror",{isFullscreen:f.IsDocumentFullscreen(),innerWidth:this._GetWindowInnerWidth(),innerHeight:this._GetWindowInnerHeight()})}_OnVisibilityChange(b){b?this._iRuntime._CancelAnimationFrame():
this._iRuntime._RequestAnimationFrame();this.PostToRuntime("visibilitychange",{hidden:b})}_OnKeyEvent(b,a){"Backspace"===a.key&&u(a);const c=g.get(a.code)||a.code;this._PostToRuntimeMaybeSync(b,{code:c,key:a.key,which:a.which,repeat:a.repeat,altKey:a.altKey,ctrlKey:a.ctrlKey,metaKey:a.metaKey,shiftKey:a.shiftKey,timeStamp:a.timeStamp},k)}_OnMouseWheelEvent(b,a){this.PostToRuntime(b,{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,
timeStamp:a.timeStamp},k)}_OnMouseEvent(b,a,c){e(a)||this._PostToRuntimeMaybeSync(b,{button:a.button,buttons:a.buttons,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,timeStamp:a.timeStamp},c)}_OnMouseEventAsPointer(b,a){if(!e(a)){var c=this._mousePointerLastButtons;"pointerdown"===b&&0!==c?b="pointermove":"pointerup"===b&&0!==a.buttons&&(b="pointermove");this._PostToRuntimeMaybeSync(b,{pointerId:1,pointerType:"mouse",button:a.button,buttons:a.buttons,lastButtons:c,clientX:a.clientX,
clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:a.timeStamp},k);this._mousePointerLastButtons=a.buttons;this._OnMouseEvent(a.type,a,r)}}_OnPointerEvent(b,a){this._pointerRawUpdateRateLimiter&&"pointermove"!==b&&this._pointerRawUpdateRateLimiter.Reset();var c=0;"mouse"===a.pointerType&&(c=this._mousePointerLastButtons);this._PostToRuntimeMaybeSync(b,{pointerId:a.pointerId,pointerType:a.pointerType,button:a.button,buttons:a.buttons,
lastButtons:c,clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,width:a.width||0,height:a.height||0,pressure:a.pressure||0,tangentialPressure:a.tangentialPressure||0,tiltX:a.tiltX||0,tiltY:a.tiltY||0,twist:a.twist||0,timeStamp:a.timeStamp},k);"mouse"===a.pointerType&&(c="mousemove","pointerdown"===b?c="mousedown":"pointerup"===b&&(c="mouseup"),this._OnMouseEvent(c,a,r),this._mousePointerLastButtons=a.buttons)}_OnPointerRawUpdate(b){this._lastPointerRawUpdateEvent=b;this._pointerRawUpdateRateLimiter.Call()}_DoSendPointerRawUpdate(){this._OnPointerEvent("pointermove",
this._lastPointerRawUpdateEvent);this._lastPointerRawUpdateEvent=null}_OnTouchEvent(b,a){for(let c=0,d=a.changedTouches.length;c<d;++c){const h=a.changedTouches[c];this._PostToRuntimeMaybeSync(b,{pointerId:h.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:2*(h.radiusX||h.webkitRadiusX||0),height:2*(h.radiusY||h.webkitRadiusY||0),pressure:h.force||h.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:h.rotationAngle||
0,timeStamp:a.timeStamp},k)}}_HandlePointerDownFocus(b){window!==window.top&&window.focus();this._IsElementCanvasOrDocument(b.target)&&document.activeElement&&!this._IsElementCanvasOrDocument(document.activeElement)&&document.activeElement.blur()}_IsElementCanvasOrDocument(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}_AttachDeviceOrientationEvent(){this._attachedDeviceOrientationEvent||(this._attachedDeviceOrientationEvent=!0,window.addEventListener("deviceorientation",
b=>this._OnDeviceOrientation(b)),window.addEventListener("deviceorientationabsolute",b=>this._OnDeviceOrientationAbsolute(b)))}_AttachDeviceMotionEvent(){this._attachedDeviceMotionEvent||(this._attachedDeviceMotionEvent=!0,window.addEventListener("devicemotion",b=>this._OnDeviceMotion(b)))}_OnDeviceOrientation(b){this.PostToRuntime("deviceorientation",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp,webkitCompassHeading:b.webkitCompassHeading,webkitCompassAccuracy:b.webkitCompassAccuracy},
k)}_OnDeviceOrientationAbsolute(b){this.PostToRuntime("deviceorientationabsolute",{absolute:!!b.absolute,alpha:b.alpha||0,beta:b.beta||0,gamma:b.gamma||0,timeStamp:b.timeStamp},k)}_OnDeviceMotion(b){let a=null;var c=b.acceleration;c&&(a={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var d=b.accelerationIncludingGravity;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;const h=b.rotationRate;h&&(d={alpha:h.alpha||0,beta:h.beta||0,gamma:h.gamma||0});this.PostToRuntime("devicemotion",{acceleration:a,accelerationIncludingGravity:c,
rotationRate:d,interval:b.interval,timeStamp:b.timeStamp},k)}_OnUpdateCanvasSize(b){const a=this.GetRuntimeInterface().GetCanvas();a.style.width=b.styleWidth+"px";a.style.height=b.styleHeight+"px";a.style.marginLeft=b.marginLeft+"px";a.style.marginTop=b.marginTop+"px";this._isFirstSizeUpdate&&(a.style.display="",this._isFirstSizeUpdate=!1)}_OnInvokeDownload(b){const a=b.url;b=b.filename;const c=document.createElement("a"),d=document.body;c.textContent=b;c.href=a;c.download=b;d.appendChild(c);c.click();
d.removeChild(c)}async _OnRasterSvgImage(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async _OnGetSvgImageSize(b){return await self.C3_GetSvgImageSize(b.blob)}async _OnAddStylesheet(b){await p(b.url)}_PlayPendingMedia(){var b=[...this._mediaPendingPlay];this._mediaPendingPlay.clear();if(!this._isSilent)for(const a of b)(b=
a.play())&&b.catch(c=>{this._mediaRemovedPendingPlay.has(a)||this._mediaPendingPlay.add(a)})}TryPlayMedia(b){if("function"!==typeof b.play)throw Error("missing play function");this._mediaRemovedPendingPlay.delete(b);let a;try{a=b.play()}catch(c){this._mediaPendingPlay.add(b);return}a&&a.catch(c=>{this._mediaRemovedPendingPlay.has(b)||this._mediaPendingPlay.add(b)})}RemovePendingPlay(b){this._mediaPendingPlay.delete(b);this._mediaRemovedPendingPlay.add(b)}SetSilent(b){this._isSilent=!!b}_OnHideCordovaSplash(){navigator.splashscreen&&
navigator.splashscreen.hide&&navigator.splashscreen.hide()}_OnDebugHighlight(b){if(b.show){this._debugHighlightElem||(this._debugHighlightElem=document.createElement("div"),this._debugHighlightElem.id="inspectOutline",document.body.appendChild(this._debugHighlightElem));var a=this._debugHighlightElem;a.style.display="";a.style.left=b.left-1+"px";a.style.top=b.top-1+"px";a.style.width=b.width+2+"px";a.style.height=b.height+2+"px";a.textContent=b.name}else this._debugHighlightElem&&(this._debugHighlightElem.style.display=
"none")}_OnRegisterSW(){window.C3_RegisterSW&&window.C3_RegisterSW()}_OnPostToDebugger(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}_InvokeFunctionFromJS(b,a){return this.PostToRuntimeAsync("js-invoke-function",{name:b,params:a})}_OnAlert(b){alert(b.message)}_OnWrapperMessage(b){"entered-fullscreen"===b?(f._SetWrapperIsFullscreenFlag(!0),this._OnFullscreenChange()):"exited-fullscreen"===b?(f._SetWrapperIsFullscreenFlag(!1),this._OnFullscreenChange()):console.warn("Unknown wrapper message: ",
b)}})}"use strict";
self.JobSchedulerDOM=class{constructor(f){this._runtimeInterface=f;this._baseUrl=f.GetBaseURL();"preview"===f.GetExportType()?this._baseUrl+="c3/workers/":this._baseUrl+=f.GetScriptFolder();this._maxNumWorkers=Math.min(navigator.hardwareConcurrency||2,16);this._dispatchWorker=null;this._jobWorkers=[];this._outputPort=this._inputPort=null}async Init(){if(this._hasInitialised)throw Error("already initialised");this._hasInitialised=!0;var f=this._runtimeInterface._GetWorkerURL("dispatchworker.js");this._dispatchWorker=
await this._runtimeInterface.CreateWorker(f,this._baseUrl,{name:"DispatchWorker"});f=new MessageChannel;this._inputPort=f.port1;this._dispatchWorker.postMessage({type:"_init","in-port":f.port2},[f.port2]);this._outputPort=await this._CreateJobWorker()}async _CreateJobWorker(){const f=this._jobWorkers.length;var e=this._runtimeInterface._GetWorkerURL("jobworker.js");e=await this._runtimeInterface.CreateWorker(e,this._baseUrl,{name:"JobWorker"+f});const g=new MessageChannel,k=new MessageChannel;this._dispatchWorker.postMessage({type:"_addJobWorker",
port:g.port1},[g.port1]);e.postMessage({type:"init",number:f,"dispatch-port":g.port2,"output-port":k.port2},[g.port2,k.port2]);this._jobWorkers.push(e);return k.port1}GetPortData(){return{inputPort:this._inputPort,outputPort:this._outputPort,maxNumWorkers:this._maxNumWorkers}}GetPortTransferables(){return[this._inputPort,this._outputPort]}};"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.RuntimeInterface({useWorker:!0,workerMainUrl:"workermain.js",engineScripts:["scripts/c3runtime.js"],projectScripts:[],mainProjectScript:"",scriptFolder:"scripts/",workerDependencyScripts:[],exportType:"html5"}));"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(f){super(f,"mouse");this.AddRuntimeMessageHandler("cursor",e=>this._OnChangeCursorStyle(e))}_OnChangeCursorStyle(f){document.documentElement.style.cursor=f}});"use strict";
self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMHandler{constructor(f){super(f,"touch");this.AddRuntimeMessageHandler("request-permission",e=>this._OnRequestPermission(e))}async _OnRequestPermission(f){f=f.type;let e=!0;0===f?e=await this._RequestOrientationPermission():1===f&&(e=await this._RequestMotionPermission());this.PostToRuntime("permission-result",{type:f,result:e})}async _RequestOrientationPermission(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;
try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}async _RequestMotionPermission(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}});"use strict";
{function f(e){return e&&!e.paused&&!e.ended&&0<e.currentTime}self.RuntimeInterface.AddDOMHandlerClass(class extends self.DOMElementHandler{constructor(e){super(e,"video");this.SetAutoAttach(!1);this._supportsRvfc=this._isRuntimeInWorker=!1;this._numVideos=this._sequenceNumber=0;this._destroyedVideos=new WeakSet;this.AddRuntimeMessageHandler("init",g=>this._OnInit(g));this.AddDOMElementMessageHandler("play",g=>this._OnPlay(g));this.AddDOMElementMessageHandler("pause",g=>this._OnPause(g));this.AddDOMElementMessageHandler("set-source",
(g,k)=>this._OnSetSource(g,k));this.AddDOMElementMessageHandler("set-playback-time",(g,k)=>this._OnSetPlaybackTime(g,k));this.AddDOMElementMessageHandler("set-looping",(g,k)=>this._OnSetLooping(g,k));this.AddDOMElementMessageHandler("set-muted",(g,k)=>this._OnSetMuted(g,k));this.AddDOMElementMessageHandler("set-volume",(g,k)=>this._OnSetVolume(g,k));self.C3Video_GetElement=g=>this.GetElementById(g)}async _OnInit(e){this._isRuntimeInWorker=e.isInWorker;e=document.createElement("video");this._supportsRvfc=
!!e.requestVideoFrameCallback;return{"video/webm":!!e.canPlayType("video/webm"),"video/ogg":!!e.canPlayType("video/ogg"),"video/mp4":!!e.canPlayType("video/mp4")}}TryPlayMedia(e){this._iRuntime.TryPlayMedia(e);this._isRuntimeInWorker&&this._supportsRvfc&&-1===e.c3_rvfcId&&(e.c3_rvfcId=e.requestVideoFrameCallback(()=>this._OnVideoFrameCallback(e)))}RemovePendingPlay(e){this._iRuntime.RemovePendingPlay(e);this._isRuntimeInWorker&&this._supportsRvfc&&-1!==e.c3_rvfcId&&(e.cancelVideoFrameCallback(e.c3_rvfcId),
e.c3_rvfcId=-1)}async _OnVideoFrameCallback(e){if(!this._destroyedVideos.has(e)){e.c3_rvfcId=e.requestVideoFrameCallback(()=>this._OnVideoFrameCallback(e));try{const g=e.c3_sequenceNumber++,k=await createImageBitmap(e);g>e.c3_lastFrameSequence&&(e.c3_imageBitmap=k,e.c3_lastFrameSequence=g)}catch(g){}}}CreateElement(e,g){const k=document.createElement("video");k.crossOrigin="anonymous";k.playsInline=!0;k.c3_imageBitmap=null;k.c3_rvfcId=-1;k.c3_sequenceNumber=0;k.c3_lastFrameSequence=-1;k.addEventListener("canplay",
()=>this._SendPlaybackEvent(k,e,0));k.addEventListener("canplaythrough",()=>this._SendPlaybackEvent(k,e,1));k.addEventListener("ended",()=>this._SendPlaybackEvent(k,e,2));k.addEventListener("error",()=>this._SendPlaybackEvent(k,e,3));k.addEventListener("loadstart",()=>this._SendPlaybackEvent(k,e,4));k.addEventListener("playing",()=>this._SendPlaybackEvent(k,e,5));k.addEventListener("pause",()=>this._SendPlaybackEvent(k,e,6));k.addEventListener("stalled",()=>this._SendPlaybackEvent(k,e,7));const r=
g.autoplay;0===r?(k.autoplay=!1,k.preload="none"):1===r?(k.autoplay=!1,k.preload="auto"):k.autoplay=!0;g.src&&(k.src=g.src);2===r&&this.TryPlayMedia(k);this._numVideos++;this._StartTicking();return k}_SendPlaybackEvent(e,g,k){this._destroyedVideos.has(e)||this.PostToRuntimeElement("playback-event",g,{type:k})}UpdateState(e,g){}DestroyElement(e){this.RemovePendingPlay(e);f(e)&&e.pause();e.src="";this._numVideos=Math.max(this._numVideos-1,0);0===this._numVideos&&this._StopTicking();this._destroyedVideos.add(e)}_OnPlay(e){this.TryPlayMedia(e)}_OnPause(e){this.RemovePendingPlay(e);
e.pause()}_OnSetSource(e,g){e.src=g.src;e.load()}_OnSetPlaybackTime(e,g){try{e.currentTime=g.time}catch(k){console.error("[Video] Exception setting playback time: ",k)}}_OnSetLooping(e,g){e.loop=g.isLooping}_OnSetMuted(e,g){e.muted=g.isMuted}_OnSetVolume(e,g){e.volume=g.volume}Tick(){const e={},g={sequenceNumber:this._sequenceNumber++,videoData:e},k=[],r=[];for(const [y,p]of this._elementMap.entries()){const v={currentTime:p.currentTime,duration:p.duration,videoWidth:p.videoWidth,videoHeight:p.videoHeight};
if(this._isRuntimeInWorker)if(this._supportsRvfc){const q=p.c3_imageBitmap;p.c3_imageBitmap=null;(v.imageBitmap=q)&&k.push(q)}else r.push(createImageBitmap(p).then(q=>{v.imageBitmap=q;k.push(q)}).catch(q=>{v.imageBitmap=null}));e[y.toString()]=v}Promise.all(r).then(()=>this.PostToRuntime("state",g,!1,k))}})};
